// Generated by gencpp from file unitree_legged_msgs/HighCmd.msg
// DO NOT EDIT!


#ifndef UNITREE_LEGGED_MSGS_MESSAGE_HIGHCMD_H
#define UNITREE_LEGGED_MSGS_MESSAGE_HIGHCMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <unitree_legged_msgs/BmsCmd.h>
#include <unitree_legged_msgs/LED.h>

namespace unitree_legged_msgs
{
template <class ContainerAllocator>
struct HighCmd_
{
  typedef HighCmd_<ContainerAllocator> Type;

  HighCmd_()
    : head()
    , levelFlag(0)
    , frameReserve(0)
    , SN()
    , version()
    , bandWidth(0)
    , mode(0)
    , gaitType(0)
    , speedLevel(0)
    , footRaiseHeight(0.0)
    , bodyHeight(0.0)
    , position()
    , euler()
    , velocity()
    , yawSpeed(0.0)
    , bms()
    , led()
    , wirelessRemote()
    , reserve(0)
    , crc(0)  {
      head.assign(0);

      SN.assign(0);

      version.assign(0);

      position.assign(0.0);

      euler.assign(0.0);

      velocity.assign(0.0);

      wirelessRemote.assign(0);
  }
  HighCmd_(const ContainerAllocator& _alloc)
    : head()
    , levelFlag(0)
    , frameReserve(0)
    , SN()
    , version()
    , bandWidth(0)
    , mode(0)
    , gaitType(0)
    , speedLevel(0)
    , footRaiseHeight(0.0)
    , bodyHeight(0.0)
    , position()
    , euler()
    , velocity()
    , yawSpeed(0.0)
    , bms(_alloc)
    , led()
    , wirelessRemote()
    , reserve(0)
    , crc(0)  {
  (void)_alloc;
      head.assign(0);

      SN.assign(0);

      version.assign(0);

      position.assign(0.0);

      euler.assign(0.0);

      velocity.assign(0.0);

      led.assign( ::unitree_legged_msgs::LED_<ContainerAllocator> (_alloc));

      wirelessRemote.assign(0);
  }



   typedef boost::array<uint8_t, 2>  _head_type;
  _head_type head;

   typedef uint8_t _levelFlag_type;
  _levelFlag_type levelFlag;

   typedef uint8_t _frameReserve_type;
  _frameReserve_type frameReserve;

   typedef boost::array<uint32_t, 2>  _SN_type;
  _SN_type SN;

   typedef boost::array<uint32_t, 2>  _version_type;
  _version_type version;

   typedef uint16_t _bandWidth_type;
  _bandWidth_type bandWidth;

   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef uint8_t _gaitType_type;
  _gaitType_type gaitType;

   typedef uint8_t _speedLevel_type;
  _speedLevel_type speedLevel;

   typedef float _footRaiseHeight_type;
  _footRaiseHeight_type footRaiseHeight;

   typedef float _bodyHeight_type;
  _bodyHeight_type bodyHeight;

   typedef boost::array<float, 2>  _position_type;
  _position_type position;

   typedef boost::array<float, 3>  _euler_type;
  _euler_type euler;

   typedef boost::array<float, 2>  _velocity_type;
  _velocity_type velocity;

   typedef float _yawSpeed_type;
  _yawSpeed_type yawSpeed;

   typedef  ::unitree_legged_msgs::BmsCmd_<ContainerAllocator>  _bms_type;
  _bms_type bms;

   typedef boost::array< ::unitree_legged_msgs::LED_<ContainerAllocator> , 4>  _led_type;
  _led_type led;

   typedef boost::array<uint8_t, 40>  _wirelessRemote_type;
  _wirelessRemote_type wirelessRemote;

   typedef uint32_t _reserve_type;
  _reserve_type reserve;

   typedef uint32_t _crc_type;
  _crc_type crc;





  typedef boost::shared_ptr< ::unitree_legged_msgs::HighCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::unitree_legged_msgs::HighCmd_<ContainerAllocator> const> ConstPtr;

}; // struct HighCmd_

typedef ::unitree_legged_msgs::HighCmd_<std::allocator<void> > HighCmd;

typedef boost::shared_ptr< ::unitree_legged_msgs::HighCmd > HighCmdPtr;
typedef boost::shared_ptr< ::unitree_legged_msgs::HighCmd const> HighCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::unitree_legged_msgs::HighCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::unitree_legged_msgs::HighCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::unitree_legged_msgs::HighCmd_<ContainerAllocator1> & lhs, const ::unitree_legged_msgs::HighCmd_<ContainerAllocator2> & rhs)
{
  return lhs.head == rhs.head &&
    lhs.levelFlag == rhs.levelFlag &&
    lhs.frameReserve == rhs.frameReserve &&
    lhs.SN == rhs.SN &&
    lhs.version == rhs.version &&
    lhs.bandWidth == rhs.bandWidth &&
    lhs.mode == rhs.mode &&
    lhs.gaitType == rhs.gaitType &&
    lhs.speedLevel == rhs.speedLevel &&
    lhs.footRaiseHeight == rhs.footRaiseHeight &&
    lhs.bodyHeight == rhs.bodyHeight &&
    lhs.position == rhs.position &&
    lhs.euler == rhs.euler &&
    lhs.velocity == rhs.velocity &&
    lhs.yawSpeed == rhs.yawSpeed &&
    lhs.bms == rhs.bms &&
    lhs.led == rhs.led &&
    lhs.wirelessRemote == rhs.wirelessRemote &&
    lhs.reserve == rhs.reserve &&
    lhs.crc == rhs.crc;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::unitree_legged_msgs::HighCmd_<ContainerAllocator1> & lhs, const ::unitree_legged_msgs::HighCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace unitree_legged_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::unitree_legged_msgs::HighCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::unitree_legged_msgs::HighCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::unitree_legged_msgs::HighCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::unitree_legged_msgs::HighCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unitree_legged_msgs::HighCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unitree_legged_msgs::HighCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::unitree_legged_msgs::HighCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b4825051cf66ae8183b54c57dba16b66";
  }

  static const char* value(const ::unitree_legged_msgs::HighCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb4825051cf66ae81ULL;
  static const uint64_t static_value2 = 0x83b54c57dba16b66ULL;
};

template<class ContainerAllocator>
struct DataType< ::unitree_legged_msgs::HighCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "unitree_legged_msgs/HighCmd";
  }

  static const char* value(const ::unitree_legged_msgs::HighCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::unitree_legged_msgs::HighCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[2] head\n"
"uint8 levelFlag\n"
"uint8 frameReserve\n"
"\n"
"uint32[2] SN\n"
"uint32[2] version\n"
"uint16 bandWidth\n"
"uint8 mode \n"
"\n"
"uint8 gaitType		   \n"
"uint8 speedLevel			   \n"
"float32 footRaiseHeight		   \n"
"float32 bodyHeight	   \n"
"float32[2] position \n"
"float32[3] euler	   \n"
"float32[2] velocity \n"
"float32 yawSpeed				   \n"
"BmsCmd bms\n"
"LED[4] led\n"
"uint8[40] wirelessRemote\n"
"uint32 reserve\n"
"\n"
"uint32 crc\n"
"================================================================================\n"
"MSG: unitree_legged_msgs/BmsCmd\n"
"uint8 off            # off 0xA5\n"
"uint8[3] reserve\n"
"================================================================================\n"
"MSG: unitree_legged_msgs/LED\n"
"uint8 r\n"
"uint8 g\n"
"uint8 b\n"
;
  }

  static const char* value(const ::unitree_legged_msgs::HighCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::unitree_legged_msgs::HighCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.head);
      stream.next(m.levelFlag);
      stream.next(m.frameReserve);
      stream.next(m.SN);
      stream.next(m.version);
      stream.next(m.bandWidth);
      stream.next(m.mode);
      stream.next(m.gaitType);
      stream.next(m.speedLevel);
      stream.next(m.footRaiseHeight);
      stream.next(m.bodyHeight);
      stream.next(m.position);
      stream.next(m.euler);
      stream.next(m.velocity);
      stream.next(m.yawSpeed);
      stream.next(m.bms);
      stream.next(m.led);
      stream.next(m.wirelessRemote);
      stream.next(m.reserve);
      stream.next(m.crc);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HighCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::unitree_legged_msgs::HighCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::unitree_legged_msgs::HighCmd_<ContainerAllocator>& v)
  {
    s << indent << "head[]" << std::endl;
    for (size_t i = 0; i < v.head.size(); ++i)
    {
      s << indent << "  head[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.head[i]);
    }
    s << indent << "levelFlag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.levelFlag);
    s << indent << "frameReserve: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.frameReserve);
    s << indent << "SN[]" << std::endl;
    for (size_t i = 0; i < v.SN.size(); ++i)
    {
      s << indent << "  SN[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.SN[i]);
    }
    s << indent << "version[]" << std::endl;
    for (size_t i = 0; i < v.version.size(); ++i)
    {
      s << indent << "  version[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.version[i]);
    }
    s << indent << "bandWidth: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.bandWidth);
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "gaitType: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gaitType);
    s << indent << "speedLevel: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.speedLevel);
    s << indent << "footRaiseHeight: ";
    Printer<float>::stream(s, indent + "  ", v.footRaiseHeight);
    s << indent << "bodyHeight: ";
    Printer<float>::stream(s, indent + "  ", v.bodyHeight);
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.position[i]);
    }
    s << indent << "euler[]" << std::endl;
    for (size_t i = 0; i < v.euler.size(); ++i)
    {
      s << indent << "  euler[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.euler[i]);
    }
    s << indent << "velocity[]" << std::endl;
    for (size_t i = 0; i < v.velocity.size(); ++i)
    {
      s << indent << "  velocity[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.velocity[i]);
    }
    s << indent << "yawSpeed: ";
    Printer<float>::stream(s, indent + "  ", v.yawSpeed);
    s << indent << "bms: ";
    s << std::endl;
    Printer< ::unitree_legged_msgs::BmsCmd_<ContainerAllocator> >::stream(s, indent + "  ", v.bms);
    s << indent << "led[]" << std::endl;
    for (size_t i = 0; i < v.led.size(); ++i)
    {
      s << indent << "  led[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::unitree_legged_msgs::LED_<ContainerAllocator> >::stream(s, indent + "    ", v.led[i]);
    }
    s << indent << "wirelessRemote[]" << std::endl;
    for (size_t i = 0; i < v.wirelessRemote.size(); ++i)
    {
      s << indent << "  wirelessRemote[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.wirelessRemote[i]);
    }
    s << indent << "reserve: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.reserve);
    s << indent << "crc: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.crc);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNITREE_LEGGED_MSGS_MESSAGE_HIGHCMD_H
