(cl:in-package unitree_legged_msgs-msg)
(cl:export '(HEAD-VAL
          HEAD
          LEVELFLAG-VAL
          LEVELFLAG
          FRAMERESERVE-VAL
          FRAMERESERVE
          SN-VAL
          SN
          VERSION-VAL
          VERSION
          BANDWIDTH-VAL
          BANDWIDTH
          MODE-VAL
          MODE
          GAITTYPE-VAL
          GAITTYPE
          SPEEDLEVEL-VAL
          SPEEDLEVEL
          FOOTRAISEHEIGHT-VAL
          FOOTRAISEHEIGHT
          BODYHEIGHT-VAL
          BODYHEIGHT
          POSITION-VAL
          POSITION
          EULER-VAL
          EULER
          VELOCITY-VAL
          VELOCITY
          YAWSPEED-VAL
          YAWSPEED
          BMS-VAL
          BMS
          LED-VAL
          LED
          WIRELESSREMOTE-VAL
          WIRELESSREMOTE
          RESERVE-VAL
          RESERVE
          CRC-VAL
          CRC
))