(cl:in-package unitree_legged_msgs-msg)
(cl:export '(HEAD-VAL
          HEAD
          LEVELFLAG-VAL
          LEVELFLAG
          FRAMERESERVE-VAL
          FRAMERESERVE
          SN-VAL
          SN
          VERSION-VAL
          VERSION
          BANDWIDTH-VAL
          BANDWIDTH
          IMU-VAL
          IMU
          MOTORSTATE-VAL
          MOTORSTATE
          BMS-VAL
          BMS
          FOOTFORCE-VAL
          FOOTFORCE
          FOOTFORCEEST-VAL
          FOOTFORCEEST
          MODE-VAL
          MODE
          PROGRESS-VAL
          PROGRESS
          GAITTYPE-VAL
          GAITTYPE
          FOOTRAISEHEIGHT-VAL
          FOOTRAISEHEIGHT
          POSITION-VAL
          POSITION
          BODYHEIGHT-VAL
          BODYHEIGHT
          VELOCITY-VAL
          VELOCITY
          YAWSPEED-VAL
          YAWSPEED
          RANGEOBSTACLE-VAL
          RANGEOBSTACLE
          FOOTPOSITION2BODY-VAL
          FOOTPOSITION2BODY
          FOOTSPEED2BODY-VAL
          FOOTSPEED2BODY
          WIRELESSREMOTE-VAL
          WIRELESSREMOTE
          RESERVE-VAL
          RESERVE
          CRC-VAL
          CRC
))